import { RATE, unitsForAmount, usdToZwg } from "@/lib/tariff";

/** The amounts people actually type into a ZESA calculator. Each one gets its
 *  own static page so the query "how many units is ZWG 500" has a page that
 *  answers it, with numbers regenerated by the daily tariff sync. */
export const ZWG_AMOUNTS = [50, 100, 200, 500, 1000, 2000, 5000] as const;
export const USD_AMOUNTS = [1, 2, 5, 10, 20, 50, 100] as const;

export type AmountPage = {
  slug: string;
  currency: "ZWG" | "USD";
  amount: number;
  /** Amount in ZWG, i.e. converted for USD pages at the published rate. */
  amountZwg: number;
  units: number;
  display: string;
};

function build(currency: "ZWG" | "USD", amount: number): AmountPage {
  const amountZwg = currency === "ZWG" ? amount : usdToZwg(amount);
  return {
    slug: `${currency.toLowerCase()}-${amount}`,
    currency,
    amount,
    amountZwg,
    units: unitsForAmount(amountZwg).totalUnits,
    display: currency === "ZWG" ? `ZWG ${amount.toLocaleString("en-US")}` : `US$${amount}`,
  };
}

export const AMOUNT_PAGES: AmountPage[] = [
  ...ZWG_AMOUNTS.map((a) => build("ZWG", a)),
  ...USD_AMOUNTS.map((a) => build("USD", a)),
];

export const AMOUNT_SLUGS = AMOUNT_PAGES.map((p) => p.slug);

export function findAmountPage(slug: string): AmountPage | undefined {
  return AMOUNT_PAGES.find((p) => p.slug === slug);
}

/** Neighbouring amounts in the same currency, for internal linking. */
export function siblings(page: AmountPage, count = 4): AmountPage[] {
  const same = AMOUNT_PAGES.filter((p) => p.currency === page.currency && p.slug !== page.slug);
  return same.slice(0, count);
}

export { RATE };
