import { RATE, costForUnits, unitsForAmount, usdToZwg, zwgToUsd } from "@/lib/tariff";

/** The amounts people actually type into a ZESA calculator. Each one gets its
 *  own static page so the query "how many units is ZWG 500" has a page that
 *  answers it, with numbers regenerated by the daily tariff sync. */
export const ZWG_AMOUNTS = [50, 100, 200, 500, 1000, 2000, 5000] as const;
export const USD_AMOUNTS = [1, 2, 5, 10, 20, 50, 100] as const;

export type AmountPage = {
  slug: string;
  currency: "ZWG" | "USD";
  amount: number;
  /** Amount in ZWG, i.e. converted for USD pages at the published rate. */
  amountZwg: number;
  units: number;
  display: string;
};

function build(currency: "ZWG" | "USD", amount: number): AmountPage {
  const amountZwg = currency === "ZWG" ? amount : usdToZwg(amount);
  return {
    slug: `${currency.toLowerCase()}-${amount}`,
    currency,
    amount,
    amountZwg,
    units: unitsForAmount(amountZwg).totalUnits,
    display: currency === "ZWG" ? `ZWG ${amount.toLocaleString("en-US")}` : `US$${amount}`,
  };
}

export const AMOUNT_PAGES: AmountPage[] = [
  ...ZWG_AMOUNTS.map((a) => build("ZWG", a)),
  ...USD_AMOUNTS.map((a) => build("USD", a)),
];

export const AMOUNT_SLUGS = AMOUNT_PAGES.map((p) => p.slug);

export function findAmountPage(slug: string): AmountPage | undefined {
  return AMOUNT_PAGES.find((p) => p.slug === slug);
}

/** The unit counts people actually search for ("how much is 200 units of
 *  zesa"). Each gets a static cost page, regenerated by the daily sync. */
export const UNIT_COUNTS = [50, 100, 150, 200, 250, 300, 400] as const;

export type UnitPage = {
  slug: string;
  units: number;
  costZwg: number;
  costUsd: number;
  display: string;
};

function buildUnitPage(units: number): UnitPage {
  const costZwg = costForUnits(units).totalZwg;
  return {
    slug: `${units}-units`,
    units,
    costZwg,
    costUsd: zwgToUsd(costZwg),
    display: `${units} units`,
  };
}

export const UNIT_PAGES: UnitPage[] = UNIT_COUNTS.map(buildUnitPage);

export const UNIT_SLUGS = UNIT_PAGES.map((p) => p.slug);

export function findUnitPage(slug: string): UnitPage | undefined {
  return UNIT_PAGES.find((p) => p.slug === slug);
}

/** Neighbouring unit counts, for internal linking. */
export function unitSiblings(page: UnitPage, count = 6): UnitPage[] {
  return UNIT_PAGES.filter((p) => p.slug !== page.slug).slice(0, count);
}

/** Neighbouring amounts in the same currency, for internal linking. */
export function siblings(page: AmountPage, count = 4): AmountPage[] {
  const same = AMOUNT_PAGES.filter((p) => p.currency === page.currency && p.slug !== page.slug);
  return same.slice(0, count);
}

export { RATE };
