// Build the social-share image (og.png, 1200x630) from the same tariffs.json
// the site renders. WhatsApp is a first-class share target for this site, so
// the link preview matters: it shows the brand, the live top/bottom rates and
// the stepped staircase — regenerated by every build, kept current by the
// daily tariff sync.
import fs from "node:fs";
import sharp from "sharp";

const t = JSON.parse(fs.readFileSync(new URL("../src/data/tariffs.json", import.meta.url)));
const month = new Date(t.lastVerified + "T00:00:00Z").toLocaleString("en-GB", { month: "long", year: "numeric", timeZone: "UTC" });
const fmt = (n, d = 2) => n.toLocaleString("en-US", { minimumFractionDigits: d, maximumFractionDigits: d });

const BAND_COLORS = ["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"];
const shade = (hex, f) => {
  const [r, g, b] = [1, 3, 5].map((i) => Math.round(parseInt(hex.slice(i, i + 2), 16) * f));
  return `rgb(${r},${g},${b})`;
};

// Isometric projection, screen y down.
const iso = (x, y, z) => [(x - y) * 0.866, (x + y) * 0.5 - z];
const poly = (pts, fill) =>
  `<polygon points="${pts.map(([x, y]) => `${x.toFixed(1)},${y.toFixed(1)}`).join(" ")}" fill="${fill}"/>`;

const W = 72, G = 14, HMIN = 60, HMAX = 240;
const rates = t.bands.map((b) => b.inclLevyZwg);
const [rmin, rmax] = [Math.min(...rates), Math.max(...rates)];
let bars = "";
t.bands.forEach((b, i) => {
  const h = HMIN + ((b.inclLevyZwg - rmin) / (rmax - rmin)) * (HMAX - HMIN);
  const x0 = i * (W + G), x1 = x0 + W, y0 = 0, y1 = W;
  const c = BAND_COLORS[i];
  bars += poly([iso(x1, y0, 0), iso(x1, y1, 0), iso(x1, y1, h), iso(x1, y0, h)], shade(c, 0.55)); // right
  bars += poly([iso(x0, y1, 0), iso(x1, y1, 0), iso(x1, y1, h), iso(x0, y1, h)], shade(c, 0.78)); // front
  bars += poly([iso(x0, y0, h), iso(x1, y0, h), iso(x1, y1, h), iso(x0, y1, h)], c);              // top
});

const svg = `<svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <rect width="1200" height="630" fill="#16181d"/>
  <rect x="0" y="0" width="1200" height="10" fill="#f5b800"/>
  <g font-family="Arial, Helvetica, sans-serif">
    <text x="80" y="130" font-size="34" font-weight="bold" fill="#16181d">
      <tspan dy="0"> </tspan>
    </text>
    <rect x="80" y="86" rx="8" width="118" height="52" fill="#f5b800"/>
    <text x="96" y="122" font-size="34" font-weight="bold" fill="#16181d">Volt</text>
    <text x="206" y="122" font-size="34" font-weight="bold" fill="#ffffff">ZW</text>
    <text x="80" y="240" font-size="64" font-weight="bold" fill="#ffffff">ZESA Calculator</text>
    <text x="80" y="316" font-size="64" font-weight="bold" fill="#f5b800">ZiG &amp; USD to units</text>
    <text x="80" y="390" font-size="30" fill="#ffffffb3">Tariffs ${month} — verified daily</text>
    <text x="80" y="480" font-size="26" fill="#ffffff80">ZWG ${fmt(rmin)} to ${fmt(rmax)} per unit · 6 stepped bands</text>
    <text x="80" y="530" font-size="26" fill="#ffffff80">400 kWh monthly quota · includes ${t.reaLevyPct}% REA levy</text>
  </g>
  ${(() => {
    // Fit the staircase into the right half: compute the projected bounding
    // box and derive translate/scale from it instead of eyeballing offsets.
    const pts = [];
    t.bands.forEach((b, i) => {
      const h = HMIN + ((b.inclLevyZwg - rmin) / (rmax - rmin)) * (HMAX - HMIN);
      const x0 = i * (W + G), x1 = x0 + W;
      for (const [x, y, z] of [[x0, 0, 0], [x1, W, 0], [x0, W, h], [x1, 0, h], [x1, W, h]]) pts.push(iso(x, y, z));
    });
    const xs = pts.map((p) => p[0]), ys = pts.map((p) => p[1]);
    const bw = Math.max(...xs) - Math.min(...xs), bh = Math.max(...ys) - Math.min(...ys);
    const sc = Math.min(420 / bw, 400 / bh);
    const tx = 1140 - Math.max(...xs) * sc, ty = 490 - Math.max(...ys) * sc;
    return `<g transform="translate(${tx.toFixed(1)}, ${ty.toFixed(1)}) scale(${sc.toFixed(3)})">${bars}</g>`;
  })()}
</svg>`;

// Next's file-convention image (src/app/opengraph-image.png) takes precedence
// over config metadata, so that file IS the artifact we regenerate.
await sharp(Buffer.from(svg)).png().toFile(new URL("../src/app/opengraph-image.png", import.meta.url).pathname);
console.log("opengraph-image.png regenerated");
